### PR TITLE
Changes to make LWIP work on Node 10

### PR DESCRIPTION
**Pull request by kant2002**
This is list of changes which is required to make LWIP support Node 10. I fairly sure that this is also make it work on Node 8, but have to check that. There 2 changes here:
- Update ZLib to 1.12.11
- Update source code to support latest NAN

## Update Zlib to 1.12.11
According to https://github.com/nodejs/node/commits/master/deps/zlib
this is only version except 1.2.8 which was used so far, and this should
fix  installation on 8.X and 10.X versions of Node

I'm not sure is this proper fix for, or maybe better exclude Zlib from source code and
rely on the Node-Gyp on that, that way just adding #if
and setting different values PNG_ZLIB_VERNUM make it works.

## Update source code to support latest NAN
Update code for LwipImage instantiation based on my understanding of NAN … 
- Changed constructor field declaration. I take https://github.com/nodejs/node-addon-examples/blob/master/8_passing_wrapped/nan/myobject.cc as example
- LwipImage::NewInstance is wrapped in NAN_METHOD. Again this is more based on https://github.com/nodejs/nan/blob/master/doc/object_wrappers.md
All other changes in that function is based on the way
how NAN recommendeds create new intances of wrapped objects.

### CODE REVIEW

**Comment by kant2002** [comment]
@EyalAr I personally think that it is time to drop the plug from 0.10 and 0.12, 4.x is already not supported I think and 8.X is LTS. I could change support matrix for Travis. I don't get why AppVeyor is failing, maybe due to outdated dependencies, in that case it probably force drop support of 0.10, 0.12, but that's up to you. All I want is make project installable on Node 8.X and 10.X

**Comment by EyalAr** [comment]
@kant2002 thanks for this PR!
Agree regarding dropping support for 0.10, 0.12 and 4.x.
Could you please update the support matrix?
Let's see if it also fixed the AppVeyor Build.

**Comment by kant2002** [comment]
@EyalAr I feel particularly confused with AppVeyor, now it is failing and with another reason. Could you at least give feedback on the code itself, and I will take a look at AppVeyor meanwhile.

**Comment by kant2002** [comment]
@EyalAr do you have any idea what could be done with Travis ?

**Comment by kant2002** [comment]
@EyalAr could you restart build?

**Comment by digitalica** [comment]
for me lwip breaks on node 10 too. so this looks good... (dropping support below 4 makes sense I think)

**Pull request closed without merging**
