### PR TITLE
update nan to work with io.js 2.0.0

### PR DESCRIPTION
**Pull request by jomo**
Fixes this error:

```
../node_modules/nan/nan.h:207:68: error: too many arguments to function call, expected at most 2, have 4
    return v8::Signature::New(v8::Isolate::GetCurrent(), receiver, argc, argv);
           ~~~~~~~~~~~~~~~~~~                                      ^~~~~~~~~~
```

### CODE REVIEW

**Comment by Jake0oo0** [comment]
:+1:

**Comment by th507** [comment]
Any thoughts @EyalAr?

**Comment by EyalAr** [comment]
Looks good. Switching to a more relaxed version matching is a good idea for this dep.
Let me pull and test locally and then I'll merge.

**Comment by EyalAr** [comment]
Merged. Thanks @jomo

**Comment by jomo** [comment]
Could you publish to npm? :)

**Comment by EyalAr** [comment]
I want to include a few more things in the next published version.

Could you do `npm install EyalAr/lwip#9b6d2ce` in the meantime?

**Comment by jomo** [comment]
alright, sure

**Comment by harryoh** [comment]
Hi @EyalAr 
I failed to install lwip with iojs#2.1.0 on Mac
The error is same to this issue.

It seems to be fixed but I still failed.
How can I use latest version of lwip using npm?

**Comment by jomo** [comment]
`npm install EyalAr/lwip` should work.
You can also use `EyalAr/lwip` as the version in your `package.json`

**Comment by th507** [comment]
@EyalAr Could you release a patch/minor version w/ this fix?

We have a workflow that relies on [sprity](https://github.com/sprity/sprity) which relies on [sprity-lwip](https://github.com/sprity/sprity-lwip) which relies on lwip.

Without the 'official' release, it could be quite difficult to push sprity-lwip and spritly maintainers to update their packages.

And IMHO, it's common practice to include trivia changes in a patch or even minor release. So maybe we could just fix one problem at a time and keep it going :)

**Comment by jomo** [comment]
> it's common practice to include trivia changes in a patch or even minor release.

indeed, a new published version would be nice :+1:

**Comment by pbihler** [comment]
Having `EyalAr/lwip` in the `package.json` impacts the `npm install` time badly, since it executes `node-gyp rebuild` every time (which is not that fast...), even if no changes were made to lwip.

@EyalAr Please, please publish a patch version to the npm repository!!

**Comment by NoSQLero** [comment]
@EyalAr come on, we need the latest version at NPM, please: D

**Comment by EyalAr** [comment]
OK guys, I'll release 0.0.7 today.

**Comment by EyalAr** [comment]
And on that occasion I'll add that it's really nice to see people taking such an interest in this project. Thanks.
I would appreciate any help I can get to make it even better.
I'm currently unable to give as much time as I would like to solving issues and adding features, so if anybody wants to pick up an issue and open a PR, that would be awesome.
I will also gladly give collaborator access to people who can show a good understanding of the code base.

**Comment by Jake0oo0** [comment]
Thanks for all your work on lwip, it really is a much more lightweight option compared to ImageMagik and the likes, making it so much easier to use. :heart:

**Comment by EyalAr** [comment]
https://github.com/EyalAr/lwip/releases/tag/0.0.7

**Comment by pbihler** [comment]
Thanks!

**Comment by harryoh** [comment]
Thanks!!

**Comment by NoSQLero** [comment]
Thanks :D

**Comment by gregthebusker** [comment]
Just wanted to let you know lwip doesn't work with Node 4.0.0 which just came out today.  We're using sprity, which is where our dependency stems from.

**Pull request merged**
